### ISSUE TITLE
Provision to add border to Card

### ISSUE THREAD

**Issue by kamleshchandnani** [treebohotels/leaf-ui#41]
Currently `Card` just has 2 props `color` and `elevation`. But the card should also have provision to apply border. Need to discuss about adding them to our design guidelines before even starting on this.

**Comment by srinivasdamam** [comment]
I think `box-shadow` (elevation prop) itself makes the card stand out.
I rarely saw the combination of `border` with `box-shadow`.

**Comment by kamleshchandnani** [comment]
I completely agree with you. But we have somewhere in our designs so just need to confirm it with our team once and figure out if there's really a use case for a card to have border.
