### ISSUE TITLE
Center and add space around stories in Storybook

### ISSUE THREAD

**Issue by tallpants** [treebohotels/leaf-ui#65]
### **What is the current behavior?**
Stories in Storybook are rendered starting from the default position (top left corner of the screen).

### **What is the expected behavior?**
It would be more visually appealing experience as well as give more context for components with drop shadows for example, if stories were centred and had some spacing on all sides.

### **What can be the possible solution?**
Add a Storybook decorator! I've already done this. Here's some screenshots of what the Storybook looks like this added:

<img width="1395" alt="screen shot 2018-05-03 at 5 10 42 pm" src="https://user-images.githubusercontent.com/15325890/39574780-f60471b0-4ef5-11e8-9d29-3b95c065596a.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 10 57 pm" src="https://user-images.githubusercontent.com/15325890/39574781-f639c658-4ef5-11e8-871f-89bd1c6a3a49.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 05 pm" src="https://user-images.githubusercontent.com/15325890/39574782-f66d0f40-4ef5-11e8-9694-baa7b785e04e.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 17 pm" src="https://user-images.githubusercontent.com/15325890/39574783-f6a08168-4ef5-11e8-98b2-2805eaaddbc4.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 28 pm" src="https://user-images.githubusercontent.com/15325890/39574784-f6d24cca-4ef5-11e8-826e-ca22e17adb7e.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 34 pm" src="https://user-images.githubusercontent.com/15325890/39574785-f705ca6e-4ef5-11e8-81c3-3f555a1f978f.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 42 pm" src="https://user-images.githubusercontent.com/15325890/39574786-f736b43a-4ef5-11e8-87ac-13fe2c0f0f88.png">
<img width="1395" alt="screen shot 2018-05-03 at 5 11 49 pm" src="https://user-images.githubusercontent.com/15325890/39574787-f7673ee8-4ef5-11e8-8900-005baf0026a5.png">

Pretty nice right? I've opened a PR for this [here](https://github.com/treebohotels/leaf-ui/pull/66). This is only for web and amp for now. I tried to get React Native working as well, but I ended up getting this error even on the unmodified master branch.

<img width="486" alt="screen shot 2018-05-03 at 5 51 46 pm" src="https://user-images.githubusercontent.com/15325890/39577096-fcf2c3fc-4efd-11e8-9fd4-f981f952d104.png">

 I'd be happy to make any changes you'd like!

**Comment by lakshyaranganath** [comment]
Hey @tallpants, let me be the first to welcome to leaf-ui! 🎉 We love this idea actually, let's see how we can get this merged soon :)

**Comment by kamleshchandnani** [comment]
Addressed in #66
