### ISSUE TITLE
Error on starting project on iOS simulator

### ISSUE THREAD

**Issue by manurana** [treebohotels/leaf-ui#89]
**Describe the bug**
Starting the project on an iOS sim gives an error.

**To Reproduce**
1. Follow instructions in SETUP.md for native
2. Press `i` on the expo prompt to start an iOS sim (iPhone6, iOS 11.4)
3. App starts with an error

**Expected behavior**
App should start without an error

**Screenshots**
![simulator screen shot - iphone 6 - 2018-06-10 at 23 04 53](https://user-images.githubusercontent.com/1749522/41204498-d12fd700-6d02-11e8-83cb-f7859243c643.png)

**Desktop**
 - OS: N/A
 - Browser: N/A
 - Browser Version: N/A

**Smartphone**
 - Device: iPhone6 simulator
 - OS:  iOS 11.4 (simulator)
 - Browser: N/A
 - Browser Version: N/A

**Library**
 - leaf-ui: latest github master
 - node: 8.9.0
 - npm: 5.8.0

**Additional Context**
I see the following warnings when I first run `npm install` in the app directory 
```
npm WARN @storybook/react-native@3.4.3 requires a peer of react-native@>=0.51.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.50.3 requires a peer of react@16.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by kashishgrover** [comment]
closed in #90 

Have just fixed the <Text> stories for now.
